apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-dev
  namespace: python-flask
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Sync wave to control sync order if needed
    deployment.kubernetes.io/revision: "{{now}}"  # This value will change each sync
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
        restart-on-sync: "{{now}}"  # This will also trigger a restart when the value changes
    spec:
      containers:
      - name: web-app
        image: tacksam/flask-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
