apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-dev
  namespace: python-flask
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    lastUpdateTime: "{{ now }}"  # Forces pod restart on sync
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: tacksam/flask-app:latest
        imagePullPolicy: Always  # Always pull the latest image on each deployment
        ports:
        - containerPort: 5000
