apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-dev
  namespace: python-flask
  labels:
    lastUpdated: "{{ now }}"  # This label will change with every sync
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: tacksam/flask-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
