apiVersion: apps/v1
imagePullPolicy: Always
kind: Deployment
metadata:
  name: web-app-dev
  namespace: python-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: tacksam/flask-app:dev  # Your custom Flask Docker
        ports:
        - containerPort: 5000