apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-dev
  namespace: python-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
      image: ${DOCKER_IMAGE:-tacksam/flask-app:latest}  # Use environment variable or default to your image
      imagePullPolicy: Always
      ports:
      - containerPort: 5000
