apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-dev
  namespace: python-flask
  annotations:
    kubectl.kubernetes.io/restartedAt: "{{now}}"  # Automatically update this to trigger a pod restart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: tacksam/flask-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
