apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

patches:
  - target:
      kind: Deployment
      name: web-app-dev
      namespace: python-flask  # Ensure the namespace matches your Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: web-app-dev
        namespace: python-flask
      spec:
        template:
          metadata:
            annotations:
              kubectl.kubernetes.io/restartedAt: "{{now}}"  # Automatically update this to trigger a pod restart
