apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml

configurations:
  - configmap.yaml

patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: web-app-dev
    spec:
      template:
        metadata:
          annotations:
            kubectl.kubernetes.io/restartedAt: "{{now}}"  # This will change and trigger a restart
