apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-prod
  namespace: python-flask
spec:
  replicas: 3  # Number of replicas for production environment
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: nginx:stable  # Different version for production
        ports:
        - containerPort: 80
