name: Build and Push Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2  # Use the login action
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}  # GitHub secret for Docker Hub username
        password: ${{ secrets.DOCKERHUB_TOKEN }}     # GitHub secret for Docker Hub token or password

    - name: Build the Docker image
      run: docker build -t tacksam/flask-app:${{ github.sha }} .

    - name: Push the Docker image
      run: docker push tacksam/flask-app:${{ github.sha }}
