name: Build and Push Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: docker build -t yourdockerhubusername/flask-app:${{ github.sha }} .

    - name: Push the Docker image
      run: docker push yourdockerhubusername/flask-app:${{ github.sha }}
