name: Build and Push Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: docker/login-action@v2
    - name: Login to DockerHub
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build the Docker image
      run: docker build -t tacksam/flask-app:${{ github.sha }} .

    - name: Push the Docker image
      run: docker push tacksam/flask-app:${{ github.sha }}
