name: Build and Push Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push the Docker image
      run: |
        docker build -t tacksam/flask-app:${{ github.sha }} -t tacksam/flask-app:latest .
        docker push tacksam/flask-app:${{ github.sha }}
        docker push tacksam/flask-app:latest
        