name: Build and Push Docker Image

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t tacksam/flask-app:${{ github.sha }} .
        docker push tacksam/flask-app:${{ github.sha }}

    - name: Update Kubernetes manifests with new image
      run: |
        sed -i "s|image: tacksam/flask-app.*|image: tacksam/flask-app:${{ github.sha }}|" k8s-manifests/dev/deployment.yaml
        git config --global user.email "sam.maltin@gmail.com"
        git config --global user.name "SMaltin93"
        git add k8s-manifests/dev/deployment.yaml
        git commit -m "Update image to ${{ github.sha }}"
        git push origin dev
